exp:
  wandb: true

training:
  evaluate_during_training: false
  record_evaluation_video: false
  compile_model: true
  num_epochs: 0 # 20
  num_steps: 20000 # 100000
  num_sequences: 1000
  ep_len: 120 # was 360
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  arm_loss_ratio: 1 # 100
  num_warmup_steps: 1000
  gradient_accumulation_steps: 4 # dont know how important this is

eval:
  task: widowx_put_eggplant_in_basket
  num_eval_sequences: 100
  ep_len: 360
  print_steps: 100
  save_video: false
  save_video_path: "./save/"
  save_video_name: "eval_video"

paths:
  ckpt: "./snapshot_ABC.pt"
  LMDB_path: "../calvin_lmdb/"
  save_path: "./save/"
  mae_ckpt: "./mae_pretrain_vit_base.pth"

submodel: 
  clip_backbone: "ViT-B/32"

model:
  embed_dim: 384
  n_layer: 12
  n_head: 12
  activation_function: "relu"
  dropout: 0.1
  n_positions: 1024

  perceiver:
    resampler_depth: 3
    resampler_dim_head: 128
    resampler_heads: 4
    resampler_num_latents: 9
    resampler_num_media_embeds: 1

  gpt_kwargs:
    n_layer: 12
    n_head: 12
    n_inner: 1536  # 4 * embed_dim
    activation_function: "relu"
    n_positions: 1024
    resid_pdrop: 0.1
    attn_pdrop: 0.1

  seq_len: 10

  chunk_size: 10
  act_dim: 7
  state_dim: 6
  use_hand_rgb: false
  without_norm_pixel_loss: false

  training_target:
    act_pred: true
    fwd_pred: true
    fwd_pred_hand: false

  img_feat_dim: 768
  patch_feat_dim: 768
  lang_feat_dim: 512

model_other:
  device: "cuda"
  fwd_pred_next_n: 3
  action_mode: "ee_rel_pose"
  skip_frame: 3
  test_chunk_size: 1


data:
  bs_per_gpu: 32
  workers_per_gpu: 7
  prefetch_factor: 2
  preprocess:
    rgb_static_pad: 10
    rgb_gripper_pad: 4
    rgb_shape: [224, 224]
    rgb_mean: [0.485, 0.456, 0.406]
    rgb_std: [0.229, 0.224, 0.225]
